<a href="https://colab.research.google.com/github/malojighorpade/NewclassifiactionUsing-LSTM_RNN/blob/main/FakeNewsClassifiactionUsingLstmRnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/fake_news_dataset.csv')

In [ ]:
df

,title,author,text,label
0,Study Finds quantum computing Linked to Improv...,Amanda Martinez,"According to quarterly earnings reports, Amazo...",0
1,Congress Passes Bipartisan Bill on infrastructure,David Thompson,Scientists affiliated with NASA's Jet Propulsi...,0
2,"Local Community Raises $4.5,000 for youth educ...",Washington Bureau,"According to quarterly earnings reports, JPMor...",0
3,Scientists Discover traditional values Causes ...,AmericaFirst_News,The so-called experts have been lying to us ab...,1
4,Researchers Develop New Treatment for Alzheimer's,Christopher Lee,Scientists affiliated with NASA's Jet Propulsi...,0
...,...,...,...,...
19995,National Park Service Announces Expansion of T...,Stephanie Robinson,The Federal Reserve announced a policy adjustm...,0
19996,City Council Approves New red meat Infrastruct...,Sarah Johnson,"According to quarterly earnings reports, Amazo...",0
19997,George Soros Caught Funding the globalists to ...,GreatAwakeningNews,Citizens in multiple states are reporting that...,1
19998,the EU Preparing Secret Attack Using cash money,FreedomReporter,Sources close to the situation have revealed t...,1
19999,Study: Regular Exercise Reduces diabetes Risk ...,James Wilson,The Federal Reserve announced a policy adjustm...,0

In [ ]:
df.isnull()

       title  author   text  label
0      False   False  False  False
1      False   False  False  False
2      False   False  False  False
3      False   False  False  False
4      False   False  False  False
...      ...     ...    ...    ...
19995  False   False  False  False
19996  False   False  False  False
19997  False   False  False  False
19998  False   False  False  False
19999  False   False  False  False

[20000 rows x 4 columns]

In [ ]:
df.shape

(20000, 4)

In [ ]:
X=df.drop('label',axis=1)

In [ ]:
y=df['label']

In [ ]:
X.shape

(19974, 3)

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size=7000

In [ ]:
messages=X.copy()

In [ ]:
messages['text'][1]

"Scientists affiliated with NASA's Jet Propulsion Laboratory announced confirmation of previously undetected geological activity on Mars, opening new avenues for understanding planetary formation. Officials have not yet responded to requests for further comment."

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
corpus = []
for i in range(0, len(messages)):

    review = re.sub('[^a-zA-Z0-9]', ' ', messages['text'][i])
    review=review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['accord quarterli earn report amazon exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat find subject peer review',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ mar open new avenu understand planetari format offici yet respond request comment',
 'accord quarterli earn report jpmorgan exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat addit data expect releas next quarter',
 'call expert lie us cash money begin thousand document obtain underground network confirm worst fear concern citizen mainstream media never report',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ europa open new avenu understand planetari format report made avail public onlin',
 'trade agreement sign japan australia expect reduc tariff agricultur export technolog good benefit industri nation next decad find subject peer review',
 'peer review studi publish natur found particip maintain regular physic activ show 50 lower risk develop cardiovascular complic five year follow period find subject peer review',
 'sourc close situat reveal trump secretli meet year mainstream media refus cover bombshel stori patriot share everywher get censor mainstream media never report',
 'sourc close situat reveal obama secretli control year mainstream media refus cover bombshel stori patriot share everywher get censor patriot across countri demand answer',
 'bipartisan group lawmak reach compromis agreement cybersecur legisl week negoti bill expect receiv vote full chamber end month find subject peer review',
 'feder reserv announc polici adjust follow latest meet cite ongo concern inflat labor market condit analyst expect chang impact borrow cost come month offici yet respond request comment',
 'public health offici cdc held joint brief address question covid 19 prevent treatment option offici emphas import vaccin earli detect stakehold expect meet next month',
 'local offici confirm new ai infrastructur project approv follow environment review construct expect begin spring creat approxim 200 job find subject peer review',
 'feder reserv announc polici adjust follow latest meet cite ongo concern inflat labor market condit analyst expect chang impact borrow cost come month find subject peer review',
 'intern memo leak russia govern reveal shock plot elimin christian coordin effort shadow govern biggest stori decad want see mainstream media never report',
 'share get delet truth free speech final come establish terrifi 47 doctor research mysteri silenc speak mainstream media never report',
 'bipartisan group lawmak reach compromis agreement healthcar legisl week negoti bill expect receiv vote full chamber end month find subject peer review',
 'sourc close situat reveal trump secretli control year mainstream media refus cover bombshel stori patriot share everywher get censor mainstream media never report',
 'accord quarterli earn report googl exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat find subject peer review',
 'call expert lie us christian begin thousand document obtain underground network confirm worst fear concern citizen patriot across countri demand answer',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ moon open new avenu understand planetari format stakehold expect meet next month',
 'sourc close situat reveal biden secretli plot year mainstream media refus cover bombshel stori patriot share everywher get censor patriot across countri demand answer',
 'accord quarterli earn report googl exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat report made avail public onlin',
 'citizen multipl state report tradit valu secretli introduc govern oper coordin program oper sinc 2035 zero media coverag mainstream media never report',
 'public health offici cdc held joint brief address question heart diseas prevent treatment option offici emphas import vaccin earli detect stakehold expect meet next month',
 'commun organ rais 25 000 local youth educ initi support busi individu donor contribut throughout month long campaign offici yet respond request comment',
 'public health offici cdc held joint brief address question cancer prevent treatment option offici emphas import vaccin earli detect stakehold expect meet next month',
 'doctor silenc discov gmo corn actual use mutat popul big pharma paid billion keep inform suppress patriot across countri demand answer',
 'intern memo leak israel govern reveal shock plot destroy red meat coordin effort illuminati biggest stori decad want see patriot across countri demand answer',
 'trade agreement sign germani brazil expect reduc tariff agricultur export technolog good benefit industri nation next decad stakehold expect meet next month',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ titan open new avenu understand planetari format addit data expect releas next quarter',
 'share get delet truth privat properti final come establish terrifi 47 doctor research mysteri silenc speak mainstream media never report',
 'bipartisan group lawmak reach compromis agreement cybersecur legisl week negoti bill expect receiv vote full chamber end month stakehold expect meet next month',
 'new evid emerg prove mainstream narr covid 19 complet fabric real caus known decad suppress pharmaceut compani worth trillion mainstream media never report',
 'bipartisan group lawmak reach compromis agreement infrastructur legisl week negoti bill expect receiv vote full chamber end month find subject peer review',
 'whistleblow come forward shock document prove deep state plan control privat properti across entir countri deliber hidden american public share everyon know take',
 'globalist elit use privat properti tool control manipul mass thousand peopl alreadi woken truth globalist work hard silenc patriot across countri demand answer',
 'intern memo leak china govern reveal shock plot elimin red meat coordin effort illuminati biggest stori decad want see suppress power interest',
 'trade agreement sign canada india expect reduc tariff agricultur export technolog good benefit industri nation next decad report made avail public onlin',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ enceladu open new avenu understand planetari format addit data expect releas next quarter',
 'bipartisan group lawmak reach compromis agreement immigr legisl week negoti bill expect receiv vote full chamber end month stakehold expect meet next month',
 'whistleblow come forward shock document prove deep state plan ban tradit valu across entir countri deliber hidden american public mainstream media never report',
 'peer review studi publish natur found particip maintain regular physic activ show 1 8 lower risk develop cardiovascular complic five year follow period offici yet respond request comment',
 'anonym insid top level clearanc confirm mani alreadi suspect musk directli link illuminati conspir interest everyday american share everyon know take',
 'call expert lie us red meat begin thousand document obtain underground network confirm worst fear concern citizen share everyon know take',
 'bipartisan group lawmak reach compromis agreement infrastructur legisl week negoti bill expect receiv vote full chamber end month report made avail public onlin',
 'call expert lie us privat properti begin thousand document obtain underground network confirm worst fear concern citizen share everyon know take',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ moon open new avenu understand planetari format find subject peer review',
 'new evid emerg prove mainstream narr diabet complet fabric real caus known decad suppress pharmaceut compani worth trillion patriot across countri demand answer',
 'share get delet truth cash money final come establish terrifi 47 doctor research mysteri silenc speak suppress power interest',
 'feder reserv announc polici adjust follow latest meet cite ongo concern inflat labor market condit analyst expect chang impact borrow cost come month addit data expect releas next quarter',
 'bipartisan group lawmak reach compromis agreement immigr legisl week negoti bill expect receiv vote full chamber end month report made avail public onlin',
 'new evid emerg prove mainstream narr heart diseas complet fabric real caus known decad suppress pharmaceut compani worth trillion patriot across countri demand answer',
 'accord quarterli earn report microsoft exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat offici yet respond request comment',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ titan open new avenu understand planetari format stakehold expect meet next month',
 'commun organ rais 1 8 000 local food bank initi support busi individu donor contribut throughout month long campaign stakehold expect meet next month',
 'intern memo leak china govern reveal shock plot track cash money coordin effort elit biggest stori decad want see research wake truth',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ titan open new avenu understand planetari format offici yet respond request comment',
 'bipartisan group lawmak reach compromis agreement infrastructur legisl week negoti bill expect receiv vote full chamber end month report made avail public onlin',
 'anonym insid top level clearanc confirm mani alreadi suspect trump directli link cabal meet interest everyday american share everyon know take',
 'globalist elit use cryptocurr tool control manipul mass thousand peopl alreadi woken truth globalist work hard silenc research wake truth',
 'trade agreement sign brazil india expect reduc tariff agricultur export technolog good benefit industri nation next decad offici yet respond request comment',
 'sourc close situat reveal soro secretli control year mainstream media refus cover bombshel stori patriot share everywher get censor mainstream media never report',
 'trade agreement sign india india expect reduc tariff agricultur export technolog good benefit industri nation next decad addit data expect releas next quarter',
 'whistleblow come forward shock document prove deep state plan forc free speech across entir countri deliber hidden american public share everyon know take',
 'commun organ rais 30 000 local veteran support initi support busi individu donor contribut throughout month long campaign report made avail public onlin',
 'intern memo leak russia govern reveal shock plot replac cash money coordin effort elit biggest stori decad want see patriot across countri demand answer',
 'doctor silenc discov dairi actual use poison popul big pharma paid billion keep inform suppress suppress power interest',
 'globalist elit use cash money tool control manipul mass thousand peopl alreadi woken truth elit work hard silenc share everyon know take',
 'sourc close situat reveal trump secretli control year mainstream media refus cover bombshel stori patriot share everywher get censor suppress power interest',
 'accord quarterli earn report googl exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat offici yet respond request comment',
 'citizen multipl state report christian secretli introduc govern oper coordin program oper sinc 2030 zero media coverag patriot across countri demand answer',
 'public health offici cdc held joint brief address question autism prevent treatment option offici emphas import vaccin earli detect find subject peer review',
 'research australia univers publish find journal medicin suggest statist signific correl quantum comput improv mental health outcom adult 50 addit data expect releas next quarter',
 'local offici confirm new renew energi infrastructur project approv follow environment review construct expect begin spring creat approxim 200 job find subject peer review',
 'call expert lie us cryptocurr begin thousand document obtain underground network confirm worst fear concern citizen research wake truth',
 'peer review studi publish natur found particip maintain regular physic activ show 0 5 lower risk develop cardiovascular complic five year follow period offici yet respond request comment',
 'new evid emerg prove mainstream narr covid 19 complet fabric real caus known decad suppress pharmaceut compani worth trillion suppress power interest',
 'public health offici cdc held joint brief address question cancer prevent treatment option offici emphas import vaccin earli detect stakehold expect meet next month',
 'commun organ rais 4 5 000 local cancer research initi support busi individu donor contribut throughout month long campaign report made avail public onlin',
 'new evid emerg prove mainstream narr covid 19 complet fabric real caus known decad suppress pharmaceut compani worth trillion share everyon know take',
 'globalist elit use privat properti tool control manipul mass thousand peopl alreadi woken truth globalist work hard silenc share everyon know take',
 'anonym insid top level clearanc confirm mani alreadi suspect obama directli link illuminati lie interest everyday american mainstream media never report',
 'intern memo leak israel govern reveal shock plot replac cash money coordin effort illuminati biggest stori decad want see research wake truth',
 'share get delet truth cash money final come establish terrifi 47 doctor research mysteri silenc speak patriot across countri demand answer',
 'intern memo leak iran govern reveal shock plot control cash money coordin effort deep state biggest stori decad want see mainstream media never report',
 'local offici confirm new renew energi infrastructur project approv follow environment review construct expect begin spring creat approxim 200 job stakehold expect meet next month',
 'anonym insid top level clearanc confirm mani alreadi suspect gate directli link elit manipul interest everyday american patriot across countri demand answer',
 'citizen multipl state report privat properti secretli introduc govern oper coordin program oper sinc 2025 zero media coverag patriot across countri demand answer',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ europa open new avenu understand planetari format offici yet respond request comment',
 'doctor silenc discov red meat actual use poison popul big pharma paid billion keep inform suppress share everyon know take',
 'local offici confirm new ai infrastructur project approv follow environment review construct expect begin spring creat approxim 200 job addit data expect releas next quarter',
 'whistleblow come forward shock document prove deep state plan track tradit valu across entir countri deliber hidden american public share everyon know take',
 'whistleblow come forward shock document prove deep state plan elimin cryptocurr across entir countri deliber hidden american public mainstream media never report',
 'feder reserv announc polici adjust follow latest meet cite ongo concern inflat labor market condit analyst expect chang impact borrow cost come month addit data expect releas next quarter',
 'intern memo leak iran govern reveal shock plot replac tradit valu coordin effort cabal biggest stori decad want see mainstream media never report',
 'public health offici cdc held joint brief address question diabet prevent treatment option offici emphas import vaccin earli detect report made avail public onlin',
 'scientist affili nasa jet propuls laboratori announc confirm previous undetect geolog activ enceladu open new avenu understand planetari format find subject peer review',
 'new evid emerg prove mainstream narr diabet complet fabric real caus known decad suppress pharmaceut compani worth trillion research wake truth',
 'globalist elit use cryptocurr tool control manipul mass thousand peopl alreadi woken truth shadow govern work hard silenc mainstream media never report',
 'call expert lie us christian begin thousand document obtain underground network confirm worst fear concern citizen share everyon know take',
 'bipartisan group lawmak reach compromis agreement educ legisl week negoti bill expect receiv vote full chamber end month offici yet respond request comment',
 'accord quarterli earn report tesla exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat report made avail public onlin',
 'trade agreement sign japan franc expect reduc tariff agricultur export technolog good benefit industri nation next decad report made avail public onlin',
 'share get delet truth free speech final come establish terrifi 47 doctor research mysteri silenc speak suppress power interest',
 'call expert lie us christian begin thousand document obtain underground network confirm worst fear concern citizen mainstream media never report',
 'sourc close situat reveal hillari secretli plot year mainstream media refus cover bombshel stori patriot share everywher get censor research wake truth',
 'doctor silenc discov alcohol actual use transform popul big pharma paid billion keep inform suppress suppress power interest',
 'globalist elit use free speech tool control manipul mass thousand peopl alreadi woken truth illuminati work hard silenc share everyon know take',
 'call expert lie us cash money begin thousand document obtain underground network confirm worst fear concern citizen mainstream media never report',
 'new evid emerg prove mainstream narr autism complet fabric real caus known decad suppress pharmaceut compani worth trillion research wake truth',
 'feder reserv announc polici adjust follow latest meet cite ongo concern inflat labor market condit analyst expect chang impact borrow cost come month report made avail public onlin',
 'whistleblow come forward shock document prove deep state plan elimin red meat across entir countri deliber hidden american public patriot across countri demand answer',
 'anonym insid top level clearanc confirm mani alreadi suspect hillari directli link elit hide interest everyday american research wake truth',
 'new evid emerg prove mainstream narr heart diseas complet fabric real caus known decad suppress pharmaceut compani worth trillion patriot across countri demand answer',
 'accord quarterli earn report jpmorgan exceed analyst expect strong growth cloud comput advertis segment despit headwind currenc fluctuat report made avail public onlin',
 'anonym insid top level clearanc confirm mani alreadi suspect soro directli link deep state manipul interest everyday american mainstream media never report',
 'doctor silenc discov alcohol actual use transform popul big pharma paid billion keep inform suppress research wake truth',
 'feder reserv announc polici adjust follow latest meet cite ongo concern inflat labor market condit analyst expect chang impact borrow cost come month offici yet respond request comment',
 'new evid emerg prove mainstream narr diabet complet fabric real caus known decad suppress pharmaceut compani worth trillion research wake truth',
 'call expert lie us cryptocurr begin thousand document obtain underground network confirm worst fear concern citizen mainstream media never report',
 'bipartisan group lawmak reach compromis agreement infrastructur legisl week negoti bill expect receiv vote full chamber end month find subject peer review',
 'feder reserv announc polici adjust follow latest meet cite ongo concern inflat labor market condit analyst expect chang impact borrow cost come month find subject peer review',
 'research uk univers publish find journal medicin suggest statist signific correl ai improv mental health outcom adult 50 stakehold expect meet next month',

In [ ]:
onehot_repr=[one_hot(i,voc_size)for i in corpus]
onehot_repr

[[1538,
  4343,
  3714,
  108,
  6919,
  664,
  1658,
  31,
  6866,
  2839,
  6353,
  465,
  2992,
  244,
  2714,
  1352,
  4989,
  1569,
  6420,
  2216,
  6080,
  6539],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  2469,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  4839,
  4762,
  1072,
  1898,
  2786],
 [1538,
  4343,
  3714,
  108,
  5576,
  664,
  1658,
  31,
  6866,
  2839,
  6353,
  465,
  2992,
  244,
  2714,
  1352,
  4989,
  1569,
  1335,
  2091,
  31,
  3523,
  3020,
  5188],
 [6793,
  1950,
  636,
  496,
  5976,
  448,
  2324,
  4681,
  22,
  5214,
  4675,
  783,
  4232,
  4143,
  1804,
  469,
  276,
  3977,
  459,
  292,
  108],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  6399,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  108,
  6556,
  3538,
  6038,
  1812],
 [4686,
  825,
  4016,
  5084,
  2495,
  31,
  5273,
  6932,
  2572,
  2687,
  500,
  290,
  5913,
  5305,
  4070,
  3020,
  591,
  6420,
  2216,
  6080,
  6539],
 [6080,
  6539,
  273,
  5626,
  4771,
  5061,
  4771,
  3539,
  4335,
  4441,
  2215,
  2616,
  862,
  5012,
  4787,
  596,
  3892,
  1808,
  1982,
  81,
  3628,
  3152,
  6420,
  2216,
  6080,
  6539],
 [2266,
  5760,
  3409,
  633,
  3217,
  3401,
  806,
  81,
  3977,
  459,
  235,
  3445,
  1326,
  5468,
  5640,
  5382,
  833,
  747,
  2868,
  3977,
  459,
  292,
  108],
 [2266,
  5760,
  3409,
  633,
  3440,
  3401,
  2939,
  81,
  3977,
  459,
  235,
  3445,
  1326,
  5468,
  5640,
  5382,
  833,
  747,
  2868,
  5640,
  4635,
  4297,
  6808,
  621],
 [2569,
  265,
  6295,
  1912,
  6049,
  825,
  4118,
  4156,
  1659,
  3284,
  6836,
  31,
  5824,
  4631,
  2478,
  851,
  248,
  2111,
  6420,
  2216,
  6080,
  6539],
 [5220,
  3882,
  4501,
  3180,
  881,
  3628,
  387,
  806,
  6821,
  5525,
  469,
  1135,
  5870,
  3346,
  4207,
  1658,
  31,
  537,
  5315,
  2394,
  1485,
  609,
  2111,
  4839,
  4762,
  1072,
  1898,
  2786],
 [6038,
  1387,
  4839,
  341,
  769,
  6783,
  2054,
  2581,
  4946,
  1269,
  861,
  5042,
  864,
  4205,
  4839,
  1598,
  400,
  2175,
  749,
  596,
  4164,
  31,
  806,
  3020,
  2111],
 [1423,
  4839,
  4232,
  1614,
  3717,
  3664,
  3011,
  4310,
  3628,
  4625,
  6539,
  1670,
  31,
  2324,
  1266,
  1824,
  4016,
  1930,
  3734,
  6420,
  2216,
  6080,
  6539],
 [5220,
  3882,
  4501,
  3180,
  881,
  3628,
  387,
  806,
  6821,
  5525,
  469,
  1135,
  5870,
  3346,
  4207,
  1658,
  31,
  537,
  5315,
  2394,
  1485,
  609,
  2111,
  6420,
  2216,
  6080,
  6539],
 [2323,
  5540,
  2732,
  6665,
  483,
  633,
  4283,
  494,
  6162,
  441,
  2104,
  3321,
  6856,
  483,
  4569,
  5468,
  591,
  887,
  6866,
  3977,
  459,
  292,
  108],
 [5382,
  747,
  6511,
  5177,
  4884,
  1968,
  5100,
  609,
  5899,
  6575,
  3252,
  3338,
  3752,
  5893,
  24,
  4988,
  3977,
  459,
  292,
  108],
 [2569,
  265,
  6295,
  1912,
  6049,
  825,
  1933,
  4156,
  1659,
  3284,
  6836,
  31,
  5824,
  4631,
  2478,
  851,
  248,
  2111,
  6420,
  2216,
  6080,
  6539],
 [2266,
  5760,
  3409,
  633,
  3217,
  3401,
  2939,
  81,
  3977,
  459,
  235,
  3445,
  1326,
  5468,
  5640,
  5382,
  833,
  747,
  2868,
  3977,
  459,
  292,
  108],
 [1538,
  4343,
  3714,
  108,
  3656,
  664,
  1658,
  31,
  6866,
  2839,
  6353,
  465,
  2992,
  244,
  2714,
  1352,
  4989,
  1569,
  6420,
  2216,
  6080,
  6539],
 [6793,
  1950,
  636,
  496,
  441,
  2324,
  4681,
  22,
  5214,
  4675,
  783,
  4232,
  4143,
  1804,
  469,
  276,
  5640,
  4635,
  4297,
  6808,
  621],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  6123,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  4164,
  31,
  806,
  3020,
  2111],
 [2266,
  5760,
  3409,
  633,
  2141,
  3401,
  494,
  81,
  3977,
  459,
  235,
  3445,
  1326,
  5468,
  5640,
  5382,
  833,
  747,
  2868,
  5640,
  4635,
  4297,
  6808,
  621],
 [1538,
  4343,
  3714,
  108,
  3656,
  664,
  1658,
  31,
  6866,
  2839,
  6353,
  465,
  2992,
  244,
  2714,
  1352,
  4989,
  1569,
  108,
  6556,
  3538,
  6038,
  1812],
 [276,
  5452,
  3677,
  108,
  2972,
  5301,
  3401,
  4274,
  483,
  6710,
  2104,
  5873,
  6710,
  235,
  761,
  3971,
  459,
  4843,
  3977,
  459,
  292,
  108],
 [6038,
  1387,
  4839,
  341,
  769,
  6783,
  2054,
  2581,
  4946,
  4274,
  434,
  5042,
  864,
  4205,
  4839,
  1598,
  400,
  2175,
  749,
  596,
  4164,
  31,
  806,
  3020,
  2111],
 [4205,
  6768,
  2901,
  5474,
  2817,
  1423,
  3613,
  2968,
  4171,
  5071,
  25,
  5610,
  4681,
  2548,
  6159,
  2111,
  1445,
  6358,
  4839,
  4762,
  1072,
  1898,
  2786],
 [6038,
  1387,
  4839,
  341,
  769,
  6783,
  2054,
  2581,
  4946,
  1094,
  5042,
  864,
  4205,
  4839,
  1598,
  400,
  2175,
  749,
  596,
  4164,
  31,
  806,
  3020,
  2111],
 [3338,
  24,
  3179,
  2092,
  1727,
  6104,
  3843,
  1487,
  6846,
  3276,
  4515,
  2051,
  3926,
  3717,
  1217,
  5078,
  5640,
  4635,
  4297,
  6808,
  621],
 [2323,
  5540,
  2732,
  6087,
  483,
  633,
  4283,
  494,
  3974,
  4097,
  2430,
  2104,
  3321,
  6977,
  4569,
  5468,
  591,
  887,
  6866,
  5640,
  4635,
  4297,
  6808,
  621],
 [4686,
  825,
  4016,
  4866,
  5200,
  31,
  5273,
  6932,
  2572,
  2687,
  500,
  290,
  5913,
  5305,
  4070,
  3020,
  591,
  4164,
  31,
  806,
  3020,
  2111],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  24,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  1335,
  2091,
  31,
  3523,
  3020,
  5188],
 [5382,
  747,
  6511,
  5177,
  214,
  1240,
  5100,
  609,
  5899,
  6575,
  3252,
  3338,
  3752,
  5893,
  24,
  4988,
  3977,
  459,
  292,
  108],
 [2569,
  265,
  6295,
  1912,
  6049,
  825,
  4118,
  4156,
  1659,
  3284,
  6836,
  31,
  5824,
  4631,
  2478,
  851,
  248,
  2111,
  4164,
  31,
  806,
  3020,
  2111],
 [1614,
  3,
  6342,
  375,
  3977,
  1357,
  1269,
  861,
  1992,
  4309,
  3423,
  696,
  2956,
  591,
  5078,
  5990,
  3357,
  412,
  4897,
  3977,
  459,
  292,
  108],
 [2569,
  265,
  6295,
  1912,
  6049,
  825,
  3664,
  4156,
  1659,
  3284,
  6836,
  31,
  5824,
  4631,
  2478,
  851,
  248,
  2111,
  6420,
  2216,
  6080,
  6539],
 [1107,
  609,
  3014,
  4283,
  22,
  375,
  1412,
  3677,
  3978,
  2939,
  214,
  1240,
  4635,
  6057,
  4297,
  3930,
  2897,
  504,
  6038,
  5382,
  6605,
  1007,
  4887],
 [3172,
  2214,
  3843,
  214,
  1240,
  529,
  2939,
  933,
  5076,
  4681,
  4304,
  3547,
  1331,
  5177,
  3172,
  3430,
  3604,
  24,
  5640,
  4635,
  4297,
  6808,
  621],
 [2323,
  5540,
  2732,
  5063,
  483,
  633,
  4283,
  494,
  6162,
  4097,
  2430,
  2104,
  3321,
  6977,
  4569,
  5468,
  591,
  887,
  6866,
  5078,
  6970,
  6337],
 [4686,
  825,
  4016,
  3,
  437,
  31,
  5273,
  6932,
  2572,
  2687,
  500,
  290,
  5913,
  5305,
  4070,
  3020,
  591,
  108,
  6556,
  3538,
  6038,
  1812],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  4862,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  1335,
  2091,
  31,
  3523,
  3020,
  5188],
 [2569,
  265,
  6295,
  1912,
  6049,
  825,
  1115,
  4156,
  1659,
  3284,
  6836,
  31,
  5824,
  4631,
  2478,
  851,
  248,
  2111,
  4164,
  31,
  806,
  3020,
  2111],
 [1107,
  609,
  3014,
  4283,
  22,
  375,
  1412,
  3677,
  3978,
  5967,
  2972,
  5301,
  4635,
  6057,
  4297,
  3930,
  2897,
  504,
  6038,
  3977,
  459,
  292,
  108],
 [6080,
  6539,
  273,
  5626,
  4771,
  5061,
  4771,
  3539,
  4335,
  4441,
  2215,
  2616,
  2562,
  733,
  5012,
  4787,
  596,
  3892,
  1808,
  1982,
  81,
  3628,
  3152,
  4839,
  4762,
  1072,
  1898,
  2786],
 [6530,
  1796,
  919,
  5171,
  6653,
  4232,
  3091,
  3547,
  3593,
  5524,
  135,
  4052,
  6977,
  607,
  6337,
  3044,
  504,
  5382,
  6605,
  1007,
  4887],
 [6793,
  1950,
  636,
  496,
  4097,
  2430,
  2324,
  4681,
  22,
  5214,
  4675,
  783,
  4232,
  4143,
  1804,
  469,
  276,
  5382,
  6605,
  1007,
  4887],
 [2569,
  265,
  6295,
  1912,
  6049,
  825,
  3664,
  4156,
  1659,
  3284,
  6836,
  31,
  5824,
  4631,
  2478,
  851,
  248,
  2111,
  108,
  6556,
  3538,
  6038,
  1812],
 [6793,
  1950,
  636,
  496,
  214,
  1240,
  2324,
  4681,
  22,
  5214,
  4675,
  783,
  4232,
  4143,
  1804,
  469,
  276,
  5382,
  6605,
  1007,
  4887],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  6123,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  6420,
  2216,
  6080,
  6539],
 [1614,
  3,
  6342,
  375,
  3977,
  1357,
  4713,
  1992,
  4309,
  3423,
  696,
  2956,
  591,
  5078,
  5990,
  3357,
  412,
  4897,
  5640,
  4635,
  4297,
  6808,
  621],
 [5382,
  747,
  6511,
  5177,
  5976,
  448,
  5100,
  609,
  5899,
  6575,
  3252,
  3338,
  3752,
  5893,
  24,
  4988,
  5078,
  6970,
  6337],
 [5220,
  3882,
  4501,
  3180,
  881,
  3628,
  387,
  806,
  6821,
  5525,
  469,
  1135,
  5870,
  3346,
  4207,
  1658,
  31,
  537,
  5315,
  2394,
  1485,
  609,
  2111,
  1335,
  2091,
  31,
  3523,
  3020,
  5188],
 [2569,
  265,
  6295,
  1912,
  6049,
  825,
  1115,
  4156,
  1659,
  3284,
  6836,
  31,
  5824,
  4631,
  2478,
  851,
  248,
  2111,
  108,
  6556,
  3538,
  6038,
  1812],
 [1614,
  3,
  6342,
  375,
  3977,
  1357,
  4274,
  434,
  1992,
  4309,
  3423,
  696,
  2956,
  591,
  5078,
  5990,
  3357,
  412,
  4897,
  5640,
  4635,
  4297,
  6808,
  621],
 [1538,
  4343,
  3714,
  108,
  1872,
  664,
  1658,
  31,
  6866,
  2839,
  6353,
  465,
  2992,
  244,
  2714,
  1352,
  4989,
  1569,
  4839,
  4762,
  1072,
  1898,
  2786],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  24,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  4164,
  31,
  806,
  3020,
  2111],
 [4205,
  6768,
  2901,
  2562,
  733,
  2817,
  1423,
  6526,
  5271,
  4171,
  5071,
  25,
  5610,
  4681,
  2548,
  6159,
  2111,
  1445,
  6358,
  4164,
  31,
  806,
  3020,
  2111],
 [2323,
  5540,
  2732,
  5063,
  483,
  633,
  4283,
  494,
  2077,
  5976,
  448,
  2104,
  3321,
  2214,
  4569,
  5468,
  591,
  887,
  6866,
  3752,
  5710,
  5177],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  24,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  4839,
  4762,
  1072,
  1898,
  2786],
 [2569,
  265,
  6295,
  1912,
  6049,
  825,
  3664,
  4156,
  1659,
  3284,
  6836,
  31,
  5824,
  4631,
  2478,
  851,
  248,
  2111,
  108,
  6556,
  3538,
  6038,
  1812],
 [6530,
  1796,
  919,
  5171,
  6653,
  4232,
  3091,
  3547,
  3593,
  3217,
  135,
  4052,
  1130,
  806,
  6337,
  3044,
  504,
  5382,
  6605,
  1007,
  4887],
 [3172,
  2214,
  3843,
  1477,
  529,
  2939,
  933,
  5076,
  4681,
  4304,
  3547,
  1331,
  5177,
  3172,
  3430,
  3604,
  24,
  3752,
  5710,
  5177],
 [4686,
  825,
  4016,
  5200,
  437,
  31,
  5273,
  6932,
  2572,
  2687,
  500,
  290,
  5913,
  5305,
  4070,
  3020,
  591,
  4839,
  4762,
  1072,
  1898,
  2786],
 [2266,
  5760,
  3409,
  633,
  2230,
  3401,
  2939,
  81,
  3977,
  459,
  235,
  3445,
  1326,
  5468,
  5640,
  5382,
  833,
  747,
  2868,
  3977,
  459,
  292,
  108],
 [4686,
  825,
  4016,
  437,
  437,
  31,
  5273,
  6932,
  2572,
  2687,
  500,
  290,
  5913,
  5305,
  4070,
  3020,
  591,
  1335,
  2091,
  31,
  3523,
  3020,
  5188],
 [1107,
  609,
  3014,
  4283,
  22,
  375,
  1412,
  3677,
  3978,
  703,
  4884,
  1968,
  4635,
  6057,
  4297,
  3930,
  2897,
  504,
  6038,
  5382,
  6605,
  1007,
  4887],
 [4205,
  6768,
  2901,
  241,
  2817,
  1423,
  2965,
  5071,
  4171,
  5071,
  25,
  5610,
  4681,
  2548,
  6159,
  2111,
  1445,
  6358,
  108,
  6556,
  3538,
  6038,
  1812],
 [2323,
  5540,
  2732,
  6665,
  483,
  633,
  4283,
  494,
  333,
  5976,
  448,
  2104,
  3321,
  2214,
  4569,
  5468,
  591,
  887,
  6866,
  5640,
  4635,
  4297,
  6808,
  621],
 [3338,
  24,
  3179,
  2854,
  6104,
  3843,
  933,
  6846,
  3276,
  4515,
  2051,
  3926,
  3717,
  1217,
  5078,
  5078,
  6970,
  6337],
 [3172,
  2214,
  3843,
  5976,
  448,
  529,
  2939,
  933,
  5076,
  4681,
  4304,
  3547,
  1331,
  5177,
  2214,
  3430,
  3604,
  24,
  5382,
  6605,
  1007,
  4887],
 [2266,
  5760,
  3409,
  633,
  3217,
  3401,
  2939,
  81,
  3977,
  459,
  235,
  3445,
  1326,
  5468,
  5640,
  5382,
  833,
  747,
  2868,
  5078,
  6970,
  6337],
 [1538,
  4343,
  3714,
  108,
  3656,
  664,
  1658,
  31,
  6866,
  2839,
  6353,
  465,
  2992,
  244,
  2714,
  1352,
  4989,
  1569,
  4839,
  4762,
  1072,
  1898,
  2786],
 [276,
  5452,
  3677,
  108,
  441,
  3401,
  4274,
  483,
  6710,
  2104,
  5873,
  6710,
  235,
  4323,
  3971,
  459,
  4843,
  5640,
  4635,
  4297,
  6808,
  621],
 [6038,
  1387,
  4839,
  341,
  769,
  6783,
  2054,
  2581,
  4946,
  1111,
  5042,
  864,
  4205,
  4839,
  1598,
  400,
  2175,
  749,
  596,
  6420,
  2216,
  6080,
  6539],
 [3752,
  2495,
  2737,
  5626,
  6420,
  2314,
  3697,
  3777,
  2877,
  2719,
  6367,
  6435,
  465,
  5110,
  2146,
  1387,
  5983,
  6432,
  862,
  1335,
  2091,
  31,
  3523,
  3020,
  5188],
 [1423,
  4839,
  4232,
  1614,
  6937,
  6806,
  3664,
  3011,
  4310,
  3628,
  4625,
  6539,
  1670,
  31,
  2324,
  1266,
  1824,
  4016,
  1930,
  3734,
  6420,
  2216,
  6080,
  6539],
 [6793,
  1950,
  636,
  496,
  1477,
  2324,
  4681,
  22,
  5214,
  4675,
  783,
  4232,
  4143,
  1804,
  469,
  276,
  3752,
  5710,
  5177],
 [6080,
  6539,
  273,
  5626,
  4771,
  5061,
  4771,
  3539,
  4335,
  4441,
  2215,
  2616,
  1390,
  989,
  5012,
  4787,
  596,
  3892,
  1808,
  1982,
  81,
  3628,
  3152,
  4839,
  4762,
  1072,
  1898,
  2786],
 [1614,
  3,
  6342,
  375,
  3977,
  1357,
  1269,
  861,
  1992,
  4309,
  3423,
  696,
  2956,
  591,
  5078,
  5990,
  3357,
  412,
  4897,
  5078,
  6970,
  6337],
 [6038,
  1387,
  4839,
  341,
  769,
  6783,
  2054,
  2581,
  4946,
  1094,
  5042,
  864,
  4205,
  4839,
  1598,
  400,
  2175,
  749,
  596,
  4164,
  31,
  806,
  3020,
  2111],
 [4205,
  6768,
  2901,
  4672,
  989,
  2817,
  1423,
  1094,
  3752,
  4171,
  5071,
  25,
  5610,
  4681,
  2548,
  6159,
  2111,
  1445,
  6358,
  108,
  6556,
  3538,
  6038,
  1812],
 [1614,
  3,
  6342,
  375,
  3977,
  1357,
  1269,
  861,
  1992,
  4309,
  3423,
  696,
  2956,
  591,
  5078,
  5990,
  3357,
  412,
  4897,
  5382,
  6605,
  1007,
  4887],
 [3172,
  2214,
  3843,
  214,
  1240,
  529,
  2939,
  933,
  5076,
  4681,
  4304,
  3547,
  1331,
  5177,
  3172,
  3430,
  3604,
  24,
  5382,
  6605,
  1007,
  4887],
 [6530,
  1796,
  919,
  5171,
  6653,
  4232,
  3091,
  3547,
  3593,
  3440,
  135,
  4052,
  6977,
  636,
  6337,
  3044,
  504,
  3977,
  459,
  292,
  108],
 [2323,
  5540,
  2732,
  6087,
  483,
  633,
  4283,
  494,
  333,
  5976,
  448,
  2104,
  3321,
  6977,
  4569,
  5468,
  591,
  887,
  6866,
  3752,
  5710,
  5177],
 [5382,
  747,
  6511,
  5177,
  5976,
  448,
  5100,
  609,
  5899,
  6575,
  3252,
  3338,
  3752,
  5893,
  24,
  4988,
  5640,
  4635,
  4297,
  6808,
  621],
 [2323,
  5540,
  2732,
  6109,
  483,
  633,
  4283,
  494,
  2939,
  5976,
  448,
  2104,
  3321,
  1412,
  3677,
  4569,
  5468,
  591,
  887,
  6866,
  3977,
  459,
  292,
  108],
 [1423,
  4839,
  4232,
  1614,
  6937,
  6806,
  3664,
  3011,
  4310,
  3628,
  4625,
  6539,
  1670,
  31,
  2324,
  1266,
  1824,
  4016,
  1930,
  3734,
  4164,
  31,
  806,
  3020,
  2111],
 [6530,
  1796,
  919,
  5171,
  6653,
  4232,
  3091,
  3547,
  3593,
  1847,
  135,
  4052,
  2214,
  933,
  6337,
  3044,
  504,
  5640,
  4635,
  4297,
  6808,
  621],
 [276,
  5452,
  3677,
  108,
  214,
  1240,
  3401,
  4274,
  483,
  6710,
  2104,
  5873,
  6710,
  235,
  4419,
  3971,
  459,
  4843,
  5640,
  4635,
  4297,
  6808,
  621],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  6399,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  4839,
  4762,
  1072,
  1898,
  2786],
 [3338,
  24,
  3179,
  4097,
  2430,
  6104,
  3843,
  933,
  6846,
  3276,
  4515,
  2051,
  3926,
  3717,
  1217,
  5078,
  5382,
  6605,
  1007,
  4887],
 [1423,
  4839,
  4232,
  1614,
  3717,
  3664,
  3011,
  4310,
  3628,
  4625,
  6539,
  1670,
  31,
  2324,
  1266,
  1824,
  4016,
  1930,
  3734,
  1335,
  2091,
  31,
  3523,
  3020,
  5188],
 [1107,
  609,
  3014,
  4283,
  22,
  375,
  1412,
  3677,
  3978,
  2077,
  2972,
  5301,
  4635,
  6057,
  4297,
  3930,
  2897,
  504,
  6038,
  5382,
  6605,
  1007,
  4887],
 [1107,
  609,
  3014,
  4283,
  22,
  375,
  1412,
  3677,
  3978,
  6162,
  1477,
  4635,
  6057,
  4297,
  3930,
  2897,
  504,
  6038,
  3977,
  459,
  292,
  108],
 [5220,
  3882,
  4501,
  3180,
  881,
  3628,
  387,
  806,
  6821,
  5525,
  469,
  1135,
  5870,
  3346,
  4207,
  1658,
  31,
  537,
  5315,
  2394,
  1485,
  609,
  2111,
  1335,
  2091,
  31,
  3523,
  3020,
  5188],
 [2323,
  5540,
  2732,
  6109,
  483,
  633,
  4283,
  494,
  333,
  2972,
  5301,
  2104,
  3321,
  1130,
  4569,
  5468,
  591,
  887,
  6866,
  3977,
  459,
  292,
  108],
 [6038,
  1387,
  4839,
  341,
  769,
  6783,
  2054,
  2581,
  4946,
  4713,
  5042,
  864,
  4205,
  4839,
  1598,
  400,
  2175,
  749,
  596,
  108,
  6556,
  3538,
  6038,
  1812],
 [3893,
  2855,
  6292,
  4328,
  2804,
  6440,
  4501,
  4232,
  3396,
  6096,
  3432,
  2215,
  4862,
  1087,
  1614,
  5679,
  4080,
  6673,
  2766,
  6420,
  2216,
  6080,
  6539],
 [1614,
  3,
  6342,
  375,
  3977,
  1357,
  4713,
  1992,
  4309,
  3423,
  696,
  2956,
  591,
  5078,
  5990,
  3357,
  412,
  4897,
  3752,
  5710,
  5177],
 [3172,
  2214,
  3843,
  1477,
  529,
  2939,
  933,
  5076,
  4681,
  4304,
  3547,
  1331,
  5177,
  6856,
  483,
  3430,
  3604,
  24,
  3977,
  459,
  292,
  108],
 [6793,
  1950,
  636,
  496,
  441,
  2324,
  4681,
  22,
  5214,
  4675,
  783,
  4232,
  4143,
  1804,
  469,
  276,
  5382,
  6605,
  1007,
  4887],
 [2569,
  265,
  6295,
  1912,
  6049,
  825,
  2968,
  4156,
  1659,
  3284,
  6836,
  31,
  5824,
  4631,
  2478,
  851,
  248,
  2111,
  4839,
  4762,
  1072,
  1898,
  2786],
 [1538,
  4343,
  3714,
  108,
  3443,
  664,
  1658,
  31,
  6866,
  2839,
  6353,
  465,
  2992,
  244,
  2714,
  1352,
  4989,
  1569,
  108,
  6556,
  3538,
  6038,
  1812],
 [4686,
  825,
  4016,
  5084,
  1902,
  31,
  5273,
  6932,
  2572,
  2687,
  500,
  290,
  5913,
  5305,
  4070,
  3020,
  591,
  108,
  6556,
  3538,
  6038,
  1812],
 [5382,
  747,
  6511,
  5177,
  4884,
  1968,
  5100,
  609,
  5899,
  6575,
  3252,
  3338,
  3752,
  5893,
  24,
  4988,
  5078,
  6970,
  6337],
 [6793,
  1950,
  636,
  496,
  441,
  2324,
  4681,
  22,
  5214,
  4675,
  783,
  4232,
  4143,
  1804,
  469,
  276,
  3977,
  459,
  292,
  108],
 [2266,
  5760,
  3409,
  633,
  2358,
  3401,
  494,
  81,
  3977,
  459,
  235,
  3445,
  1326,
  5468,
  5640,
  5382,
  833,
  747,
  2868,
  3752,
  5710,
  5177],
 [3338,
  24,
  3179,
  5121,
  6104,
  3843,
  1057,
  6846,
  3276,
  4515,
  2051,
  3926,
  3717,
  1217,
  5078,
  5078,
  6970,
  6337],
 [3172,
  2214,
  3843,
  4884,
  1968,
  529,
  2939,
  933,
  5076,
  4681,
  4304,
  3547,
  1331,
  5177,
  6977,
  3430,
  3604,
  24,
  5382,
  6605,
  1007,
  4887],
 [6793,
  1950,
  636,
  496,
  5976,
  448,
  2324,
  4681,
  22,
  5214,
  4675,
  783,
  4232,
  4143,
  1804,
  469,
  276,
  3977,
  459,
  292,
  108],
 [1614,
  3,
  6342,
  375,
  3977,
  1357,
  1111,
  1992,
  4309,
  3423,
  696,
  2956,
  591,
  5078,
  5990,
  3357,
  412,
  4897,
  3752,
  5710,
  5177],
 [5220,
  3882,
  4501,
  3180,
  881,
  3628,
  387,
  806,
  6821,
  5525,
  469,
  1135,
  5870,
  3346,
  4207,
  1658,
  31,
  537,
  5315,
  2394,
  1485,
  609,
  2111,
  108,
  6556,
  3538,
  6038,
  1812],
 [1107,
  609,
  3014,
  4283,
  22,
  375,
  1412,
  3677,
  3978,
  6162,
  4097,
  2430,
  4635,
  6057,
  4297,
  3930,
  2897,

In [ ]:
corpus[9]

'bipartisan group lawmak reach compromis agreement cybersecur legisl week negoti bill expect receiv vote full chamber end month find subject peer review'

In [ ]:
onehot_repr[9]

[2569,
 265,
 6295,
 1912,
 6049,
 825,
 4118,
 4156,
 1659,
 3284,
 6836,
 31,
 5824,
 4631,
 2478,
 851,
 248,
 2111,
 6420,
 2216,
 6080,
 6539]

In [ ]:
max_lenght=30
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=max_lenght)
print(embedded_docs)

[[   0    0    0 ... 2216 6080 6539]
 [   0    0    0 ... 1072 1898 2786]
 [   0    0    0 ... 3523 3020 5188]
 ...
 [   0    0    0 ... 3752 5710 5177]
 [   0    0    0 ... 4297 6808  621]
 [   0 5220 3882 ... 3523 3020 5188]]

In [ ]:
embedded_docs[90]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3338,
         24, 3179, 4097, 2430, 6104, 3843,  933, 6846, 3276, 4515, 2051,
       3926, 3717, 1217, 5078, 5382, 6605, 1007, 4887], dtype=int32)

In [ ]:
model = Sequential()
embedding_vector_features=40
model.add(Embedding(voc_size, embedding_vector_features,input_shape=(max_lenght,)))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 30, 40)         │       280,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 336,501 (1.28 MB)

 Trainable params: 336,501 (1.28 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import numpy as np
X_final1=np.array(embedded_docs)
y_final2=np.array(y)

In [ ]:
X_final1.shape,y_final2.shape

((20000, 30), (20000,))

In [ ]:
from sklearn import model_selection
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_final1, y_final2, test_size=0.33, random_state=50
)

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 13s 60ms/step - accuracy: 1.0000 - loss: 5.4828e-06 - val_accuracy: 1.0000 - val_loss: 5.0972e-06
Epoch 2/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 12s 59ms/step - accuracy: 1.0000 - loss: 4.7416e-06 - val_accuracy: 1.0000 - val_loss: 4.4175e-06
Epoch 3/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 11s 54ms/step - accuracy: 1.0000 - loss: 4.1172e-06 - val_accuracy: 1.0000 - val_loss: 3.8433e-06
Epoch 4/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 11s 53ms/step - accuracy: 1.0000 - loss: 3.5880e-06 - val_accuracy: 1.0000 - val_loss: 3.3553e-06
Epoch 5/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 14s 66ms/step - accuracy: 1.0000 - loss: 3.1368e-06 - val_accuracy: 1.0000 - val_loss: 2.9374e-06
Epoch 6/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - accuracy: 1.0000 - loss: 2.7501e-06 - val_accuracy: 1.0000 - val_loss: 2.5790e-06
Epoch 7/10
210/210 ━━━━━━━━━━━━━━━━━━━━ 14s 67ms/step - accuracy: 1.0000 - loss: 2.4172e-06 - val_accuracy: 1.0000 - val_loss: 2.2696e-06
Epoch 8/10
 28/210 ━━━━━━━━━━━━━━━━━━━━ 7s 41ms/step - accuracy: 1.0000 - loss: 2.2536e-06

KeyboardInterrupt:

In [ ]:
model.evaluate(X_test, y_test)

207/207 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 1.0000 - loss: 2.2303e-06

[2.2303479454421904e-06, 1.0]

In [ ]:
import numpy as np
print(np.unique(y_final, return_counts=True))

(array([0, 1]), array([10043,  9957]))

In [ ]:
print(set(map(str, X_train)) & set(map(str, X_test)))

{'[   0    0    0    0    0    0    0 3893 2855 6292 4328 2804 6440 4501\n 4232 3396 6096 3432 2215 6399 1087 1614 5679 4080 6673 2766 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 2292 3401  806\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0 3172 2214 3843 4097 2430  529\n 2939  933 5076 4681 4304 3547 1331 5177 1412 3677 3430 3604   24 3752\n 5710 5177]', '[   0    0    0    0    0    0    0 3752 5084 2737 5626 6420 2314 3697\n 3777 2877 2719 6367 3717 5110 3892 1387 5983 6432  862 4839 4762 1072\n 1898 2786]', '[   0    0    0    0    0    0    0    0    0    0 3338   24 3179 4133\n 6104 3843 5560 6846 3276 4515 2051 3926 3717 1217 5078 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 2854 6104 3843 1057 6846 3276 4515 2051 3926 3717 1217 5078 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0    0 4686  825 4016 5798 4866\n   31 5273 6932 2572 2687  500  290 5913 5305 4070 3020  591 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0    0  276 5452 3677  108 1477 3401\n 4274  483 6710 2104 5873 6710  235 2916 3971  459 4843 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0    0    0 6530 1796  919 5171 6653\n 4232 3091 3547 3593 3856  135 4052 2214  607 6337 3044  504 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0    0    0    0 6793 1950  636\n  496 2156 2324 4681   22 5214 4675  783 4232 4143 1804  469  276 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0    0    0 6793 1950  636  496\n  441 2324 4681   22 5214 4675  783 4232 4143 1804  469  276 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 3752    3 2737 5626 6420 2314 3697\n 3777 2877 2719 6367 6098 5110 2146 1387 5983 6432  862  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0    0    0 1614    3 6342  375 3977 1357 1094\n 1992 4309 3423  696 2956  591 5078 5990 3357  412 4897 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0    0    0    0  276 5452 3677  108\n 2156 3401 4274  483 6710 2104 5873 6710  235 4419 3971  459 4843 3752\n 5710 5177]', '[   0    0    0    0    0    0    0 4205 6768 2901 5474 2817 1423 2965\n 5071 4171 5071   25 5610 4681 2548 6159 2111 1445 6358 4839 4762 1072\n 1898 2786]', '[   0    0    0    0    0    0    0    0 2323 5540 2732 1735  483  633\n 4283  494  703 1477 2104 3321 6856  483 4569 5468  591  887 6866 5078\n 6970 6337]', '[   0    0    0    0    0    0    0 1107  609 3014 4283   22  375 1412\n 3677 3978 5967 4884 1968 4635 6057 4297 3930 2897  504 6038 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0 2266 5760 3409  633 2358 3401\n  636   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 5078\n 6970 6337]', '[   0    0    0    0    0    0 2266 5760 3409  633 3440 3401  607   81\n 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0 3752 5084 2737 5626 6420 2314 3697 3777\n 2877 2719 6367 6937 6806 5110 5269 5983 6432  862 1335 2091   31 3523\n 3020 5188]', '[   0    0    0 6080 6539  273 5626 4771 5061 4771 3539 4335 4441 2215\n 2616 1390  989 5012 4787  596 3892 1808 1982   81 3628 3152 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0 1107  609 3014 4283   22  375 1412\n 3677 3978 2077 2972 5301 4635 6057 4297 3930 2897  504 6038 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0 3172 2214 3843  214 1240  529\n 2939  933 5076 4681 4304 3547 1331 5177 2214 3430 3604   24 3977  459\n  292  108]', '[   0    0    0    0    0    0 2266 5760 3409  633 3440 3401 5023   81\n 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 3440 3401  806\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 2230 3401  494\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 1107  609 3014 4283   22  375 1412\n 3677 3978  333 2972 5301 4635 6057 4297 3930 2897  504 6038 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0 3752 4866 2737 5626 6420 2314\n 3697 3777 2877 2719 6367 3717 5110  818 5983 6432  862 4164   31  806\n 3020 2111]', '[   0    0    0    0    0    0    0    0 4686  825 4016 4866 5084   31\n 5273 6932 2572 2687  500  290 5913 5305 4070 3020  591  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0    0    0    0 3752 5200 2737 5626 6420 2314\n 3697 3777 2877 2719 6367 3717 5110 2146 1387 5983 6432  862 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0    0 1107  609 3014 4283   22  375\n 1412 3677 3978 2077  441 4635 6057 4297 3930 2897  504 6038 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 2292 3401 2939\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 4205 6768 2901  624 2817 1423 2965\n 5071 4171 5071   25 5610 4681 2548 6159 2111 1445 6358 4164   31  806\n 3020 2111]', '[   0    0    0    0    0    0    0 4205 6768 2901  241 2817 1423 1094\n 3752 4171 5071   25 5610 4681 2548 6159 2111 1445 6358 4839 4762 1072\n 1898 2786]', '[   0    0    0 6080 6539  273 5626 4771 5061 4771 3539 4335 4441 2215\n 2616  862 5012 4787  596 3892 1808 1982   81 3628 3152 4839 4762 1072\n 1898 2786]', '[   0    0    0    0    0    0    0    0 4686  825 4016 2495 4866   31\n 5273 6932 2572 2687  500  290 5913 5305 4070 3020  591 4164   31  806\n 3020 2111]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 2292 3401 2889\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0 3172 2214 3843 4097 2430  529\n 2939  933 5076 4681 4304 3547 1331 5177 6977 3430 3604   24 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0 2266 5760 3409  633 2141 3401\n  607   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 5078\n 6970 6337]', '[   0    0    0    0 6038 1387 4839  341  769 6783 2054 2581 4946 1269\n  861 5042  864 4205 4839 1598  400 2175  749  596 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0    0    0    0    0    0 3338   24 3179 6875\n 6104 3843  933 6846 3276 4515 2051 3926 3717 1217 5078 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 2854 6104 3843 5560 6846 3276 4515 2051 3926 3717 1217 5078 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0  276 5452 3677  108 2972 5301\n 3401 4274  483 6710 2104 5873 6710  235 6067 3971  459 4843 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0    0    0    0 3338   24 3179\n 2854 6104 3843 2939 6846 3276 4515 2051 3926 3717 1217 5078 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0    0    0 6793 1950  636  496\n 2156 2324 4681   22 5214 4675  783 4232 4143 1804  469  276 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0 3893 2855 6292 4328 2804 6440 4501 4232\n 3396 6096 3432 2215 6399 1087 1614 5679 4080 6673 2766  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0    0    0 4686  825 4016 1902 1902   31 5273\n 6932 2572 2687  500  290 5913 5305 4070 3020  591 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0    0    0    0 1107  609 3014 4283   22  375\n 1412 3677 3978 6162 4884 1968 4635 6057 4297 3930 2897  504 6038 3752\n 5710 5177]', '[   0    0    0    0    0    0    0 3752 4866 2737 5626 6420 2314 3697\n 3777 2877 2719 6367 3717 5110 2146 1387 5983 6432  862  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0    0    0    0 1107  609 3014 4283   22  375\n 1412 3677 3978  333  441 4635 6057 4297 3930 2897  504 6038 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0    0    0 3338   24 3179 4097\n 2430 6104 3843 3974 6846 3276 4515 2051 3926 3717 1217 5078 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0 1107  609 3014 4283   22  375 1412\n 3677 3978 6162 5976  448 4635 6057 4297 3930 2897  504 6038 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0    0    0 6530 1796  919 5171\n 6653 4232 3091 3547 3593 3440  135 4052 1130  494 6337 3044  504 5078\n 6970 6337]', '[   0    0    0    0    0    0    0    0 1107  609 3014 4283   22  375\n 1412 3677 3978  703 2972 5301 4635 6057 4297 3930 2897  504 6038 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0    0 1614    3 6342  375 3977\n 1357 1094 1992 4309 3423  696 2956  591 5078 5990 3357  412 4897 5078\n 6970 6337]', '[   0    0    0    0    0    0    0 4686  825 4016 2351  437   31 5273\n 6932 2572 2687  500  290 5913 5305 4070 3020  591 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0    0    0    0    0  276 5452 3677  108 4884\n 1968 3401 4274  483 6710 2104 5873 6710  235 2916 3971  459 4843 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0    0 3172 2214 3843 1477  529\n 2939  933 5076 4681 4304 3547 1331 5177 6977 3430 3604   24 3977  459\n  292  108]', '[   0    0    0    0    0    0 1107  609 3014 4283   22  375 1412 3677\n 3978 3974 4097 2430 4635 6057 4297 3930 2897  504 6038 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0    0 1107  609 3014 4283   22  375\n 1412 3677 3978  703 1477 4635 6057 4297 3930 2897  504 6038 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0  276 5452 3677  108 2972 5301\n 3401 4274  483 6710 2104 5873 6710  235 2916 3971  459 4843 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 1107  609 3014 4283   22  375 1412\n 3677 3978 6162 5976  448 4635 6057 4297 3930 2897  504 6038 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0 4686  825 4016 5084 1902   31 5273\n 6932 2572 2687  500  290 5913 5305 4070 3020  591 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0    0    0    0    0    0  276 5452 3677  108\n 2156 3401 4274  483 6710 2104 5873 6710  235 4419 3971  459 4843 5078\n 6970 6337]', '[   0    0    0    0    0    0    0    0    0    0  276 5452 3677  108\n  441 3401 4274  483 6710 2104 5873 6710  235  459 3971  459 4843 5078\n 6970 6337]', '[   0    0    0    0    0    0    0    0 4686  825 4016 5798 1902   31\n 5273 6932 2572 2687  500  290 5913 5305 4070 3020  591  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0    0    0    0    0    0 5382  747 6511 5177\n 5976  448 5100  609 5899 6575 3252 3338 3752 5893   24 4988 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0 2266 5760 3409  633 2292 3401\n  607   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 5078\n 6970 6337]', '[   0    0    0    0    0 4205 6768 2901 4672  989 2817 1423 3613 2968\n 4171 5071   25 5610 4681 2548 6159 2111 1445 6358 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0    0 3752 2495 2737 5626 6420 2314 3697 3777\n 2877 2719 6367 6435  465 5110 2146 1387 5983 6432  862  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0    0 4205 6768 2901 5474 2817 1423 6526 5271\n 4171 5071   25 5610 4681 2548 6159 2111 1445 6358 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0    0    0 4205 6768 2901  624 2817 1423 2965\n 5071 4171 5071   25 5610 4681 2548 6159 2111 1445 6358  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0 1423 4839 4232 1614 6435  465 3664 3011 4310\n 3628 4625 6539 1670   31 2324 1266 1824 4016 1930 3734 4164   31  806\n 3020 2111]', '[   0    0    0    0    0    0    0    0 1107  609 3014 4283   22  375\n 1412 3677 3978   90 1477 4635 6057 4297 3930 2897  504 6038 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0    0 3172 2214 3843  214 1240\n  529 2939  933 5076 4681 4304 3547 1331 5177 6977 3430 3604   24 5078\n 6970 6337]', '[   0    0    0    0    0    0    0  276 5452 3677  108 5976  448 3401\n 4274  483 6710 2104 5873 6710  235  761 3971  459 4843 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0    0    0  276 5452 3677  108 5976\n  448 3401 4274  483 6710 2104 5873 6710  235 2916 3971  459 4843 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0 4686  825 4016 5798 5084   31\n 5273 6932 2572 2687  500  290 5913 5305 4070 3020  591 4164   31  806\n 3020 2111]', '[   0    0    0    0    0    0    0    0 3752 1902 2737 5626 6420 2314\n 3697 3777 2877 2719 6367 6098 5110  818 5983 6432  862 4164   31  806\n 3020 2111]', '[   0    0    0    0    0    0    0    0 3172 2214 3843 2156  529 2939\n  933 5076 4681 4304 3547 1331 5177 1412 3677 3430 3604   24 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 5121 6104 3843 2939 6846 3276 4515 2051 3926 3717 1217 5078 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0 6530 1796  919 5171 6653 4232\n 3091 3547 3593 3856  135 4052 6856  483 2889 6337 3044  504 3977  459\n  292  108]', '[   0    0    0    0    0    0 3752 1902 2737 5626 6420 2314 3697 3777\n 2877 2719 6367 6435  465 5110 5269 5983 6432  862 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0    0    0    0    0  276 5452 3677  108  441\n 3401 4274  483 6710 2104 5873 6710  235  459 3971  459 4843 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 3752 1902 2737 5626 6420 2314 3697\n 3777 2877 2719 6367 3717 5110  818 5983 6432  862 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0 4205 6768 2901 4672  989 2817 1423 2965 5071\n 4171 5071   25 5610 4681 2548 6159 2111 1445 6358 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0    0 4205 6768 2901 1390  989 2817 1423 1094\n 3752 4171 5071   25 5610 4681 2548 6159 2111 1445 6358 4839 4762 1072\n 1898 2786]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 6875 6104 3843 1057 6846 3276 4515 2051 3926 3717 1217 5078 3752\n 5710 5177]', '[   0    0    0    0    0    0 2569  265 6295 1912 6049  825 2968 4156\n 1659 3284 6836   31 5824 4631 2478  851  248 2111 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 4133 6104 3843 1487 6846 3276 4515 2051 3926 3717 1217 5078 5078\n 6970 6337]', '[   0    0    0    0    0    0    0    0 2323 5540 2732 5174  483  633\n 4283  494 5967 1477 2104 3321 3172 4569 5468  591  887 6866 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0 1107  609 3014 4283   22  375\n 1412 3677 3978   90 5976  448 4635 6057 4297 3930 2897  504 6038 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0    0    0    0    0 5382  747\n 6511 5177  441 5100  609 5899 6575 3252 3338 3752 5893   24 4988 3752\n 5710 5177]', '[   0    0    0    0    0    0    0 1107  609 3014 4283   22  375 1412\n 3677 3978 3974 4884 1968 4635 6057 4297 3930 2897  504 6038 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 5524 3401 2889\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 3217 3401  933\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 3752    3 2737 5626 6420 2314 3697\n 3777 2877 2719 6367 6435  465 5110 3892 1387 5983 6432  862 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0    0 3752 2495 2737 5626 6420 2314\n 3697 3777 2877 2719 6367 6098 5110  818 5983 6432  862  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0    0 3893 2855 6292 4328 2804 6440 4501 4232\n 3396 6096 3432 2215 6123 1087 1614 5679 4080 6673 2766  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 1847 3401 2889\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0    0 3752 2495 2737 5626 6420\n 2314 3697 3777 2877 2719 6367 6098 5110  818 5983 6432  862 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0 1107  609 3014 4283   22  375 1412\n 3677 3978 2939  214 1240 4635 6057 4297 3930 2897  504 6038 3977  459\n  292  108]', '[   0    0    0    0    0    0    0    0 3172 2214 3843 4884 1968  529\n 2939  933 5076 4681 4304 3547 1331 5177 3172 3430 3604   24 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0 2569  265 6295 1912 6049  825\n 3664 4156 1659 3284 6836   31 5824 4631 2478  851  248 2111 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 4133 6104 3843 1057 6846 3276 4515 2051 3926 3717 1217 5078 5078\n 6970 6337]', '[   0    0    0    0    0    0    0    0 3172 2214 3843 4884 1968  529\n 2939  933 5076 4681 4304 3547 1331 5177 1412 3677 3430 3604   24 5078\n 6970 6337]', '[   0    0    0    0    0    0    0 4205 6768 2901  862 2817 1423 2965\n 5071 4171 5071   25 5610 4681 2548 6159 2111 1445 6358 4839 4762 1072\n 1898 2786]', '[   0    0    0    0    0    0    0    0    0 6530 1796  919 5171 6653\n 4232 3091 3547 3593 3440  135 4052 6977 2889 6337 3044  504 3977  459\n  292  108]', '[   0    0    0    0    0    0 1538 4343 3714  108 6919  664 1658   31\n 6866 2839 6353  465 2992  244 2714 1352 4989 1569 1335 2091   31 3523\n 3020 5188]', '[   0    0    0    0 6080 6539  273 5626 4771 5061 4771 3539 4335 4441\n 2215 2616 5474 5012 4787  596 3892 1808 1982   81 3628 3152 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0    0    0    0    0 3338   24 3179\n 2092 1727 6104 3843  933 6846 3276 4515 2051 3926 3717 1217 5078 5078\n 6970 6337]', '[   0    0    0    0    0    0    0    0    0    0    0 3338   24 3179\n 5121 6104 3843 2939 6846 3276 4515 2051 3926 3717 1217 5078 3977  459\n  292  108]', '[   0    0    0    0    0    0    0 4205 6768 2901 5474 2817 1423 6074\n 6743 4171 5071   25 5610 4681 2548 6159 2111 1445 6358  108 6556 3538\n 6038 1812]', '[   0    0    0    0    0    0    0    0 2266 5760 3409  633 2141 3401\n  933   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0    0    0 3338   24 3179 4133\n 6104 3843 1057 6846 3276 4515 2051 3926 3717 1217 5078 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0 2266 5760 3409  633 5524 3401  494\n   81 3977  459  235 3445 1326 5468 5640 5382  833  747 2868 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 5121 6104 3843 5560 6846 3276 4515 2051 3926 3717 1217 5078 3752\n 5710 5177]', '[   0    0    0    0    0    0    0    0    0  276 5452 3677  108 2156\n 3401 4274  483 6710 2104 5873 6710  235 4323 3971  459 4843 5382 6605\n 1007 4887]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 5121 6104 3843  933 6846 3276 4515 2051 3926 3717 1217 5078 5078\n 6970 6337]', '[   0    0    0    0    0    0 3172 2214 3843  214 1240  529 2939  933\n 5076 4681 4304 3547 1331 5177 1412 3677 3430 3604   24 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0    0    0    0    0 3338   24 3179\n 6875 6104 3843  933 6846 3276 4515 2051 3926 3717 1217 5078 5382 6605\n 1007 4887]', '[   0    0 6080 6539  273 5626 4771 5061 4771 3539 4335 4441 2215 2616\n 4672  989 5012 4787  596 3892 1808 1982   81 3628 3152 4164   31  806\n 3020 2111]', '[   0    0    0    0    0    0 1423 4839 4232 1614 6937 6806 3664 3011\n 4310 3628 4625 6539 1670   31 2324 1266 1824 4016 1930 3734 6420 2216\n 6080 6539]', '[   0    0    0    0    0    0    0    0    0    0    0    0 3338   24\n 3179 6875 6104 3843 2939 6846 3276 4515 2051 3926 3717 1217 5078 5078\n 6970 6337]', '[   0    0    0    0    0    0    0 1107  609 3014 4283   22  375 1412\n 3677 3978 2077  441 4635 6057 4297 3930 2897  504 6038 5640 4635 4297\n 6808  621]', '[   0    0    0    0    0    0    0 1614    3 6342  375 3977 1357 1111\n 1992 4309 3423  696 2956  591 5078 5990 3357  412 

In [ ]:
# Check overlap between train and test
overlap = set(map(str, X_train)) & set(map(str, X_test))
print(len(overlap))